### PR TITLE
Fixed #53

### LINKED ISSUE #53: KeyError: 'notify-subscription-id' for create_printer_subscription response
``` python
def create_printer_subscription(uri, ...):
    # ...
    return response['Tests'][0]['notify-subscription-id']
```

the return value should be changed to 

``` python
return response['Tests'][0]['ResponseAttributes'][1]['notify-subscription-id']
```

### PR DESCRIPTION
**Pull request by sbellem**

### CODE REVIEW

**Comment by ticosax** [comment]
Works for me

**Comment by sbellem** [comment]
Here is what I get:

``` python
In [32]: create_printer_subscription('https://localhost:631/', printer_uri='https://localhost:631/printers/tokamak', notify_recipient_uri='mailto:sylvain@ezeep.com')
> /Users/alaya/repos/ezeep/pyipptool/pyipptool/__init__.py(162)create_printer_subscription()
    161     ipdb.set_trace()
--> 162     return response['Tests'][0]['notify-subscription-id']
    163

ipdb> response
{'Successful': True, 'Transfer': 'auto', 'Tests': [{'ResponseAttributes': [{'attributes-charset': 'utf-8', 'attributes-natural-language': 'en'}, {'notify-subscription-id': 10}], 'Name': 'Create Printer Subscription', 'Successful': True, 'RequestAttributes': [{'requesting-user-name': 'None', 'attributes-charset': 'utf-8', 'printer-uri': 'https://localhost:631/printers/tokamak', 'attributes-natural-language': 'en'}, {'notify-recipient-uri': 'mailto:sylvain@ezeep.com', 'notify-events': 'None'}], 'Version': '1.1', 'RequestId': 6030, 'Operation': 'Create-Printer-Subscription', 'StatusCode': 'successful-ok'}], 'ipptoolVersion': 'CUPS v1.7.0'}
ipdb> response['Tests'][0]['notify-subscription-id']
*** KeyError: 'notify-subscription-id'
ipdb> response['Tests'][0]
{'ResponseAttributes': [{'attributes-charset': 'utf-8', 'attributes-natural-language': 'en'}, {'notify-subscription-id': 10}], 'Name': 'Create Printer Subscription', 'Successful': True, 'RequestAttributes': [{'requesting-user-name': 'None', 'attributes-charset': 'utf-8', 'printer-uri': 'https://localhost:631/printers/tokamak', 'attributes-natural-language': 'en'}, {'notify-recipient-uri': 'mailto:sylvain@ezeep.com', 'notify-events': 'None'}], 'Version': '1.1', 'RequestId': 6030, 'Operation': 'Create-Printer-Subscription', 'StatusCode': 'successful-ok'}
ipdb> response['Tests'][0].keys()
['ResponseAttributes', 'Name', 'Successful', 'RequestAttributes', 'Version', 'RequestId', 'Operation', 'StatusCode']
ipdb> response['Tests'][0]['ResponseAttributes']
[{'attributes-charset': 'utf-8', 'attributes-natural-language': 'en'}, {'notify-subscription-id': 10}]
ipdb> response['Tests'][0]['ResponseAttributes'][1]
{'notify-subscription-id': 10}
ipdb> response['Tests'][0]['ResponseAttributes'][1]['notify-subscription-id']
10
ipdb>
```

**Comment by ticosax** [comment]
``` python
{'Successful': True,
 'Tests': [{'Name': 'Create Printer Subscription',
            'Operation': 'Create-Printer-Subscription',
            'RequestAttributes': [{'attributes-charset': 'utf-8',
                                   'attributes-natural-language': 'en',
                                   'printer-uri': 'http://localhost:631/printers/PDF',
                                   'requesting-user-name': 'ticosax'},
                                  {'notify-events': 'all',
                                   'notify-recipient-uri': 'rss://'}],
            'ResponseAttributes': [{'attributes-charset': 'utf-8',
                                    'attributes-natural-language': 'en'},
                                   {'notify-subscription-id': 362}],
            'StatusCode': 'successful-ok',
            'Successful': True,
            'notify-subscription-id': 362}],
 'Transfer': 'auto'}
```

with ipptool delivered with cups 1.5.3, the difference comes probably from there, as you are using cups 1.7.0.

What do you suggest ?

**Comment by sbellem** [comment]
Ah okay. I am not sure. Maybe we try to find out whether we can be sure that 

``` python
response['Tests'][0]['ResponseAttributes'][1]['notify-subscription-id']
```

is reliable for all `ipptool` versions ...

I can ask on Apple's mailing list ...

What do you think?

**Pull request closed without merging**
